apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- literals:
  - password=YOUR_PASSWORD
  name: mysql-pass
resources:
- mysql-deployment.yml
- wordpress-deployment.yml
  
namePrefix: my-app-
